#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: BSD-3-Clause

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="dns-companion"

dc_bootstrap_filesystem
dc_generate_config

liftoff
