#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: BSD-3-Clause

source /container/base/functions/container/init
prepare_service 10-herald
SERVICE_NAME="herald"

herald_bootstrap_filesystem
herald_generate_config

liftoff
