# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: BSD-3-Clause

ARG \
     BASE_IMAGE

FROM ${BASE_IMAGE}

LABEL \
  org.opencontainers.image.title="Herald" \
  org.opencontainers.image.description="Modern DNS manager" \
  org.opencontainers.image.url="https://hub.docker.com/r/nfrastack/herald" \
  org.opencontainers.image.documentation="https://github.com/nfrastack/herald/blob/main/README.md" \
  org.opencontainers.image.source="https://github.com/nfrastack/herald.git" \
  org.opencontainers.image.authors="Nfrastack <code@nfrastack.com>" \
  org.opencontainers.image.vendor="Nfrastack <https://www.nfrastack.com>" \
  org.opencontainers.image.licenses="BSD-3-Clause"

ARG \
    HERALD_VERSION \
    HERALD_COMMIT \
    GOLANG_VERSION="1.26.8"

ENV \
    CONTAINER_ENABLE_SCHEDULING=TRUE \
    PATH="/app:${PATH}" \
    HERALD_USER=herald \
    HERALD_GROUP=herald \
    IMAGE_NAME="nfrastack/herald" \
    IMAGE_REPO_URL="https://github.com/nfrastack/herald"

VOLUME /state
WORKDIR /app
COPY / /usr/src/herald

HEALTHCHECK \
                --interval=30s \
                --timeout=5s \
                --start-period=60s \
                --retries=3 \
            CMD /app/herald --version || exit 1

RUN echo "" && \
    hver="${HERALD_VERSION}" && \
    if [ "${hver}" = "dev" ]; then hver=""; fi && \
    if [ -z "${hver}" ]; then \
        if [ -n "${HERALD_COMMIT}" ]; then hver="dev-${HERALD_COMMIT}"; \
        else hver="dev-$(date -u +%Y%m%d-%H%M%S)-h$(find /usr/src/herald/src /usr/src/herald/container -type f | LC_ALL=C sort | xargs sha256sum 2>/dev/null | sha256sum | cut -c1-7)"; fi && \
    fi && \
    HERALD_BUILD_DEPS_ALPINE=" \
                                make \
                          " \
                          && \
    \
    HERALD_BUILD_DEPS_DEBIAN=" \
                                make \
                          " \
                          && \
    \
    echo "" && \
    source /container/base/functions/container/build && \
    \
    mkdir -p /usr/src/container/ && \
    cp \
        /usr/src/herald/{CHANGELOG.md,LICENSE,README.md} \
                                                /usr/src/container/ \
                                                && \
    cp \
        /usr/src/herald/container/README.md \
                                                /usr/src/container/container-README.md \
                                                && \
    \
    container_build_log image && \
    \
    create_user "${HERALD_USER}" 1000 "${HERALD_GROUP}" 1000 /dev/null && \
    package update && \
    package upgrade && \
    package install \
                    HERALD_BUILD_DEPS \
                    && \
    package build go buildtime && \
    package build yq && \
    \
    cd /usr/src/herald && \
    \
    case "$(container_info arch alt)" in \
        amd64 | arm64) \
            : ; \
        ;; \
        * ) \
            echo >&2 "Error: unsupported architecture ($(container_info arch alt))" ; \
            exit 1 ; \
        ;; \
    esac ; \
    \
    make build-release HERALD_VERSION="${hver}" && \
    cp -aR \
                herald \
                LICENSE \
                LICENSES \
                README.md \
                SECURITY.md \
           /app \
           && \
    \
    cp -aR \
                /usr/src/herald/container/rootfs/*  \
            / && \
    \
    container_build_log add "Herald" "${hver}" "${HERALD_REPO_URL}" && \
    package remove \
                    HERALD_BUILD_DEPS \
                    && \
    package cleanup

