#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: BSD-3-Clause

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="container-dns-companion"

cdc_bootstrap_filesystem
cdc_generate_config

liftoff
